### ISSUE TITLE
Error Handling Mechanism

### ISSUE THREAD

**Issue by Dineshchitta** [mykolaj/Robospice-Retrofit2-sample#1]
How can we get error Response Code & error response body ?

**Comment by mykolaj** [comment]
If we use my sample as an example for this, then there's a method `loadDataFromNetwork()` in a `MessageRequest` class (don't forget that this method is already executing in a background thread, so no need to do any async stuff here):

    @Override
    public SingleMessageJson loadDataFromNetwork() throws Exception {
        return getService().getSingleMessage(mId).clone().execute().body();
    }

`getService().getSingleMessage(mId).clone().execute()` part returns a `retrofit2.Response<T>` object which has a wide set of methods itself. For example: 

    @Override
    public SingleMessageJson loadDataFromNetwork() throws Exception {
        ResponseBody errorBody = getService().getSingleMessage(mId).clone().execute().errorBody();
        ...
    }

Take a look on a documentation on `retrofit2.Response<T>` class for more methods.

**Comment by Dineshchitta** [comment]
Thank you @mykolaj I tried as You said. I modified Message Request like this. But In the Constructor super(Response<SingleMessageJson.class>,SomeWebApi.class)). I am getting error like Expression expected. Can you help me with this.Where It is correct way or Am I missing something.  

```
public class MessageRequest extends RetrofitSpiceRequest<Response<SingleMessageJson>, SomeWebApi> {

    private final long mId;

    public MessageRequest(long id) {
        super(Response<SingleMessageJson.class>, SomeWebApi.class);
        mId = id;
    }

    @Override
    public Response<SingleMessageJson> loadDataFromNetwork() throws Exception {
        return getService().getSingleMessage(mId).clone().execute();
    }

    public String getCacheKey() {
        return String.format(Locale.US, "id:%d", mId);
    }
}
```

**Comment by mykolaj** [comment]
@Dineshchitta I've updated the sample with a demo of how to approach this. 52d86ab86f93f9533a2d85e92abbed59a9183cd6

**Comment by Dineshchitta** [comment]
Thank you very much @mykolaj It is worked. :+1:
